AWSTemplateFormatVersion: '2010-09-09'
Description: Simple test stack

Parameters:
  BucketName:
    Type: String

Resources:
  TestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName



